version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: mvn clean spring-boot:run
    ports:
      - "8089:8089"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_USER: stationSki
      MYSQL_PASSWORD: P4ssword!
      MYSQL_ROOT_PASSWORD: P4ssword!
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
