version: '3'
services:
  app:
    container_name: app
    image: saleminess/ski:latest
    restart: always
    ports:
      - "8089:8089"
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_USER: stationSki
      MYSQL_PASSWORD: P4ssword!
      MYSQL_ROOT_PASSWORD: P4ssword!
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
